### PR TITLE
Fixing map variable name for #75

### LINKED ISSUE #75: Rank-aggregated CTRs not calculated
Steps to reproduce:

1. Chorus up an running
2. Generate a couple of queries and clicks
3. Generate a query set
```
java -jar ../target/search-evaluation-framework.jar -s create-query-set.json
```
Config:
```
{
  "sampler": "all",
  "name": "",
  "description": "",
  "sampling": "",
  "querySetSize": 500
}
```
4. Calculate judgments

```
java -jar ../target/search-evaluation-framework.jar -o http://localhost:9200 -c coec
```

In the OS Dev Tools run a query in the ctr index:
```
POST click_through_rates/_search
```
In the OS Dev Tools run a query in the rank-aggregated ctr index:
```
POST rank_aggregated_ctr/_search
```
Observation:
CTRs look good, rank-aggregated CTRs all 0

```
{
      "_index": "rank_aggregated_ctr",
      "_id": "1f399a9a-9ab6-41cd-8db4-818c59e760cd",
      "_score": 1,
      "_source": {
        "id": "1f399a9a-9ab6-41cd-8db4-818c59e760cd",
        "position": 0,
        "ctr": 0
      }
}
```

### PR DESCRIPTION
**Pull request by jzonthemtn**
Closes #75

### CODE REVIEW

File: src/main/java/org/opensearch/eval/engine/OpenSearchEngine.java [hunk 1]
```diff
@@ -645,8 +645,8 @@ public Map<Integer, Double> getRankAggregatedClickThrough(final int maxRank) thr
                 final List<LongTermsBucket> positionBuckets = positionTerms.lterms().buckets().array();
 
                 for(final LongTermsBucket positionBucket : positionBuckets) {
-                    LOGGER.debug("Inserting client event from position {} with click count {}", positionBucket.key(), (double) positionBucket.docCount());
-                    impressionCounts.put(Integer.valueOf(positionBucket.key()), (double) positionBucket.docCount());
+                    LOGGER.debug("Inserting click event from position {} with click count {}", positionBucket.key(), (double) positionBucket.docCount());
+                    clickCounts.put(Integer.valueOf(positionBucket.key()), (double) positionBucket.docCount());
```
Comment (jzonthemtn) [inline src/main/java/org/opensearch/eval/engine/OpenSearchEngine.java:649]: This was causing the all zeroes because it was going into the wrong map...

Comment (epugh) [reply src/main/java/org/opensearch/eval/engine/OpenSearchEngine.java:649]: nice find

File: data/esci/index.sh [hunk 2]
```diff
@@ -7,4 +7,4 @@ echo "Initializing UBI..."
 curl -s -X POST "http://localhost:9200/_plugins/ubi/initialize"
 
 echo "Indexing queries and events..."
-curl  -X POST 'http://localhost:9200/index-name/_bulk?pretty' --data-binary @ubi_queries_events.ndjson -H "Content-Type: application/x-ndjson"
\ No newline at end of file
+curl  -X POST 'http://localhost:9200/_bulk?pretty' --data-binary @ubi_queries_events.ndjson -H "Content-Type: application/x-ndjson"
```
Comment (jzonthemtn) [inline data/esci/index.sh:10]: This was bugging me @wrigleyDan and had to change it.

File: scripts/opensearch-scripts/get-rank-aggregated-ctr.sh [hunk 3]
```diff
@@ -0,0 +1,11 @@
+#!/bin/bash -e
```
Comment (jzonthemtn) [inline scripts/opensearch-scripts/get-rank-aggregated-ctr.sh:1]: Just a query to easily look for zeroes.

Comment (wrigleyDan) [reply scripts/opensearch-scripts/get-rank-aggregated-ctr.sh:1]: When this query is meant to look for zeroes shouldn't it look like this (in Dev Tools style):

```
GET rank_aggregated_ctr/_search
{
  "query": {
    "range": {
      "ctr": {
        "gte": 0,
        "lte": 0
      }
    }
  }
}
```

**Review by wrigleyDan — COMMENTED** [review]
excellent find, fixes the 0s in the rank-aggregated CTRs and as a direct consequence the implicit judgment calculation 👍 

Just one question regarding the query looking for rank-aggregated CTRs, otherwise this is done.

File: scripts/opensearch-scripts/get-rank-aggregated-ctr.sh (hunk 3 above)
Comment (jzonthemtn) [reply scripts/opensearch-scripts/get-rank-aggregated-ctr.sh:1]: Oh, sorry. Meant to look for things that are not zeroes. Since everything was 0, I wanted to look at the > 0 ones afterward.

Comment (wrigleyDan) [reply scripts/opensearch-scripts/get-rank-aggregated-ctr.sh:1]: ok, that makes sense then, thanks!

**Review by wrigleyDan — APPROVED** [review]
LGTM
